-- Generated by Oracle SQL Developer Data Modeler 4.2.0.932
--   at:        2017-05-02 22:13:25 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE building (
    id          INTEGER NOT NULL,
    name        VARCHAR2(45),
    lat         FLOAT,
    lon         FLOAT,
    editor_id   INTEGER NOT NULL
);

CREATE UNIQUE INDEX building__idx ON
    building ( editor_id ASC );

ALTER TABLE building ADD CONSTRAINT building_pk PRIMARY KEY ( id );

CREATE TABLE editor (
    id              INTEGER NOT NULL,
    user_name       VARCHAR2(45),
    user_password   VARCHAR2(61),
    last_visit      DATE
);

ALTER TABLE editor ADD CONSTRAINT editor_pk PRIMARY KEY ( id );

CREATE TABLE map (
    id             INTEGER NOT NULL,
    floor          INTEGER NOT NULL,
    image          VARCHAR2(45) NOT NULL,
    image_md5      VARCHAR2(33),
    image_width    INTEGER,
    image_height   INTEGER,
    building_id    INTEGER NOT NULL,
    editor_id      INTEGER NOT NULL
);

CREATE UNIQUE INDEX map__idx ON
    map ( editor_id ASC );

ALTER TABLE map ADD CONSTRAINT map_pk PRIMARY KEY ( id );

CREATE TABLE path (
    id              INTEGER NOT NULL,
    first_pin_id    INTEGER NOT NULL,
    second_pin_id   INTEGER NOT NULL,
    editor_id       INTEGER NOT NULL
);

CREATE UNIQUE INDEX path__idx ON
    path ( editor_id ASC );

ALTER TABLE path ADD CONSTRAINT path_pk PRIMARY KEY ( id );

CREATE TABLE pin (
    id          INTEGER NOT NULL,
    name        VARCHAR2(45),
    pos_x       FLOAT NOT NULL,
    pos_y       FLOAT,
    map_id      INTEGER NOT NULL,
    editor_id   INTEGER NOT NULL
);

CREATE UNIQUE INDEX pin__idx ON
    pin ( editor_id ASC );

ALTER TABLE pin ADD CONSTRAINT pin_pk PRIMARY KEY ( id );

ALTER TABLE building ADD CONSTRAINT building_editor_fk FOREIGN KEY ( editor_id )
    REFERENCES editor ( id );

ALTER TABLE map ADD CONSTRAINT map_building_fk FOREIGN KEY ( building_id )
    REFERENCES building ( id );

ALTER TABLE map ADD CONSTRAINT map_editor_fk FOREIGN KEY ( editor_id )
    REFERENCES editor ( id );

ALTER TABLE path ADD CONSTRAINT path_editor_fk FOREIGN KEY ( editor_id )
    REFERENCES editor ( id );

ALTER TABLE path ADD CONSTRAINT path_pin_fk FOREIGN KEY ( first_pin_id )
    REFERENCES pin ( id );

ALTER TABLE path ADD CONSTRAINT path_pin_fkv2 FOREIGN KEY ( second_pin_id )
    REFERENCES pin ( id );

ALTER TABLE pin ADD CONSTRAINT pin_editor_fk FOREIGN KEY ( editor_id )
    REFERENCES editor ( id );

ALTER TABLE pin ADD CONSTRAINT pin_map_fk FOREIGN KEY ( map_id )
    REFERENCES map ( id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             4
-- ALTER TABLE                             13
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
